"""add project_members table

Revision ID: 0c7e8a2d5c55
Revises: 8db3d186dce9
Create Date: 2026-08-07 14:34:15.562903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7e8a2d5c55'
down_revision: Union[str, Sequence[str], None] = '8db3d186dce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='project_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_id_user_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO project_members (project_id, user_id, role) "
        "SELECT id, user_id, 'owner' FROM projects"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
    op.execute(
        "UPDATE projects SET user_id = pm.user_id FROM project_members pm "
        "WHERE pm.project_id = projects.id AND pm.role = 'owner'"
    )
    op.alter_column('projects', 'user_id', nullable=False)
    op.drop_table('project_members')
    op.execute('DROP TYPE project_role')
