"""add google_id to users

Revision ID: 5da23629c0bd
Revises: 77a09b5afcf3
Create Date: 2026-08-06 09:47:02.561398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da23629c0bd'
down_revision: Union[str, Sequence[str], None] = '77a09b5afcf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
